### ISSUE TITLE
ocr-replacements - returned non-zero exit status 128

### ISSUE THREAD

**Issue by kiwilad-nz** [philiptn/mkv-auto#32]
Currently set this up in a docker container:

```
networks:
  10.10.20.x-apps:
    external: True
services:
  mkv-auto-service:
    container_name: mkv-auto
    dns:
      - 10.10.20.1
    entrypoint:
      - /bin/bash
      - /mkv-auto/service-entrypoint.sh
    image: philiptn/mkv-auto:latest
    networks:
      10.10.20.x-apps:
        ipv4_address: 10.10.20.21
    restart: unless-stopped
    tty: True
    user: '568:568'
    volumes:
      - /mnt/APPS/MKV-Auto/input:/mkv-auto/files/input
      - /mnt/APPS/MKV-Auto/output:/mkv-auto/files/output
      - /mnt/APPS/MKV-Auto/.tmp:/mkv-auto/files/tmp
      - /mnt/APPS/MKV-Auto/config:/mkv-auto/config
      - /mnt/APPS/MKV-Auto/logs:/mkv-auto/logs
```

```
root@TrueNAS[/mnt/APPS/MKV-Auto]# ls -la
total 81
drwxrwx---  7 apps apps  10 May 24 15:44 .
drwxr-xr-x 33 root root  33 May 24 14:44 ..
-rwxrwx---  1 apps apps 262 May 24 14:48 .env
drwxrwx---  2 apps apps   2 May 25 06:25 .tmp
drwxrwx---  2 apps apps   4 May 24 16:45 config
-rwxrwx---  1 apps apps 450 May 24 14:56 docker-compose.yml
drwxrwx---  2 apps apps   2 May 25 06:24 input
drwxrwx---  2 apps apps   5 May 25 06:24 logs
drwxrwx---  3 apps apps   3 May 24 16:25 output
-rwxrwx--x  1 apps apps 549 May 24 15:11 set_up_folders.sh
```

I am getting this, and am unsure if this is erroring out everything as the input file goes more or less to the output file with nothing else really reported in the logs. 

```
[DEBUG] [UTC 2025-05-24 04:25:40] [ERROR] An unknown error occured. Moving file to destination folder...
Command '['git', 'clone', 'https://github.com/philiptn/ocr-replacements.git', 'ocr-replacements']' returned non-zero exit status 128.
```

Also, will `PREFERRED_AUDIO_FORMATS = "EAC3:5.1"` transcode DTS-HD to this? If I don't specify the channels will this transcode to matching channels?
